# Generated by Django 5.2.7 on 2025-10-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.URLField(
                default="https://picsum.photos/800/600",
                max_length=500,
                verbose_name="Image principale (URL)",
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.URLField(
                default="https://picsum.photos/800/600",
                max_length=500,
                verbose_name="Image (URL)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.URLField(
                blank=True,
                default="https://picsum.photos/800/600",
                max_length=500,
                verbose_name="Image (URL)",
            ),
        ),
    ]
