# Generated by Django 5.2.7 on 2025-12-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_project_featured_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "image",
                    models.ImageField(upload_to="gallery/", verbose_name="Image"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hero", "Image héro (homepage)"),
                            ("showcase", "Vitrine"),
                            ("team", "Équipe"),
                            ("other", "Autre"),
                        ],
                        default="showcase",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Légende"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Image de galerie",
                "verbose_name_plural": "Images de galerie",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="before_image",
            field=models.ImageField(
                blank=True,
                help_text="Pour les projets avant/après",
                null=True,
                upload_to="projects/before/",
                verbose_name="Image avant (optionnel)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="has_before_after",
            field=models.BooleanField(
                default=False, verbose_name="Afficher avant/après"
            ),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="Visible"),
        ),
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projects/featured/",
                verbose_name="Image principale",
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                upload_to="projects/gallery/", verbose_name="Image"
            ),
        ),
    ]
