# Generated by Django 5.2.7 on 2025-12-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_galleryimage_project_before_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="linked_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gallery_images",
                to="core.project",
                verbose_name="Projet lié",
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="caption",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Légende/Description"
            ),
        ),
    ]
