# Generated by Django 5.2.7 on 2025-12-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_galleryimage_linked_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="address",
            field=models.TextField(blank=True, verbose_name="Adresse postale"),
        ),
    ]
