# Generated by Django 5.2.7 on 2026-03-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_contactmessage_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="image",
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(
                default="HomeRepairService",
                max_length=50,
                verbose_name="Icône Material UI (https://mui.com/material-ui/material-icons/)",
            ),
        ),
    ]
